### ISSUE TITLE
[v0.3.1] testing of build 0.3.1.v20170319-2031

### ISSUE THREAD

**Issue by anb0s** [anb0s/YAFMT#19]
I need help with testing of the build
tag: **...**
commit: **d17ad5c773ec2507a6a45f8350a7cd176ed10dca**

It is available at the testing update site now: http://anb0s.github.io/YAFMT/testing
version: **YAFMT 0.3.1.v20170319-2031**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found and open issues or enhancement requests that will be addressed in next test build:
- [x] #20 [v0.3.1] update information about new home and update site
- [x] #21 [v0.3.1] update project from JavaSE-1.6 to 1.7

new fixed issues in this build:
- [x] #9 dependency to de.itemis.xtext.utils.jface 2.1.0 cannot be resolved
- [x] #15 [dev] add target definition for all dependencies
- [x] #18 [dev] add maven (tycho) build for CI

fixed issues with previous build(s):
...

**Comment by anb0s** [comment]
next build #22
