### ISSUE TITLE
[v0.4.0] testing of build 0.4.0.v20191027-2040

### ISSUE THREAD

**Issue by anb0s** [anb0s/YAFMT#32]
I need help with testing of the build
- tag(s): ...
- commit(s): 44add4cadc1ad1677ad1f049aaf84d4007881f2f 7d7931b0c38a58fbd081211942530ecaecfed74e

It is available at the testing update site now: http://anb0s.github.io/YAFMT/testing
version: **YAFMT 0.4.0.v20191027-2040**

**Use "Help | Install New Software...", paste the link and select the right version!**

**new found and open issues or enhancement requests that will be addressed in next test build:**
- [ ] ...

**new fixed issues in this build:**
- [x] use tycho 1.5.0 and Eclipse-2019-09 platform
- [x] remov some not needed platforms (deprecated / old -> leave only "classsic" 4.8 and latest from 2018(-09) and two latest releases (2019-06 & 09)
- [x] remov oraclejdk8, because it's not supported by Travis CI anymore
- [x] #31 change license to EPL 2.0 
- [x] add Eclipse-2019-06 target platform
- [x] YAFMT does not compile with target platform Eclipse-2018-12 and greater
#30
- [x] update target platforms 2018-09 - 2019-03
- [x] remove oraclejdk10 and added openjdk11
- [x] add openjdk10 and oraclejdk10
- [x] set minimum Java 8 (JavaSE 1.8)
- [x] add Eclipse Photon 4.9 (2018-09) target platform
- [x] update Eclipse-4.8.target
- [x] add target platforms 4.7 and 4.8 to Travis CI build matrix
- [x] #1 add support of default attribute values
- [x] add more boolean checks

**fixed issues with previous build(s):**
- [x] #28 v0.4.0] testing of build 0.4.0.v20180121-1618
  - [x] #17 [dev] include the code from org.yakindu.base.xtext.utils.jface
  - [x] fixed error in constraints, because '-' is not valid character within ID
- [x] #27 [v0.4.0] testing of build 0.4.0.v20180121-1352
  - [x] impoved validator messages
  - [x] fixed some warnings
  - [x] added EMF mapping to 4.6 target platform
  - [x] improved validation of AttributeValue
    - [x] moved check methods to ValidationUtil
    - [x]  added boolean validation
  - [x] update FM validation, so it checks wheter the default value is appropriate for the given attribute type
  - [x] Travis-CI: oraclejdk7 is not supported anymore (using openjdk8 and oraclejdk8 now)
  - [x] Updated default target platform to Oxygen (4.7) and added target platform for Eclipse Photon (4.8)
  - [x] Use Tycho 1.0.0 (removed openjdk7, because new Tycho (>=0.25) needs Java 8)
- [x] #24 [v0.4.0] testing of build 0.4.0.v20170427-1144
  - [x] prepare not user changeable ID (UUID generated)
  - [x] added menues for manually fix this for attributes and features
  - [x] disabled "Generate ID from Name" menues
- [x] #23 [v0.4.0] testing of build 0.4.0.v20170425-2048
  - [x] #1 add support of default attribute values
  - [x] #21 [v0.3.1] update project from JavaSE-1.6 to 1.7
  - [x] fixed model validation error "defaultValueLiteral= BOOLEAN"
  - [x] fixed path to BooleanConstraintLanguage.genmodel
  - [x] set dependency of org.yakindu.base.xtext.utils.jface to minimum
version=2.5.0
  - [x] fixed NPE on dispose() because problemManager is null
  - [x] added more information to tooltips
  - [x] fixed Feature and Attribute ID and updated model
  - [x] added migration (mapping) for old 0.3.0 models defined by Siemens
  - [x] changed ID generation to UUID
  - [x] added model 0.4.0 and migration from 0.3.0
  - [x] updated YAFMT version to 0.4.0
- [x] #22 [v0.3.1] testing of build 0.3.1.v20170319-2117
  - [x] #20 [v0.3.1] update information about new home and update site
  - [x] #21 [v0.3.1] update project from JavaSE-1.6 to 1.7
- [x] #19 [v0.3.1] testing of build 0.3.1.v20170319-2031
  - [x] #9 dependency to de.itemis.xtext.utils.jface 2.1.0 cannot be resolved
  - [x] #15 [dev] add target definition for all dependencies
  - [x] #18 [dev] add maven (tycho) build for CI
